name: Distribute package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/prebuild.yml"

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025, ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'macos-15'
        run: |
          brew update && brew install icu4c@74 -f
          echo "PKG_CONFIG_PATH=$(brew --prefix icu4c@74)/lib/pkgconfig" >> $GITHUB_ENV

      - if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update && sudo apt-get install -y libicu-dev pkg-config

      - if: matrix.os == 'windows-2025'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 3425f537d2f01c761d2d2cff59a7577eb4f568c0

      - if: matrix.os == 'windows-2025'
        run: |
          vcpkg integrate install
          $env:VCPKG_DEFAULT_TRIPLET = 'x64-windows'
          vcpkg install icu[core,tools] --triplet $env:VCPKG_DEFAULT_TRIPLET
          echo "VCPKG_DEFAULT_TRIPLET=${env:VCPKG_DEFAULT_TRIPLET}" >> $env:GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@otocolobus-com"

      - run: npm ci --prefer-offline --no-audit --progress=false

      - run: npm run test

  publish_github_packages:
    name: Publish package to GitHub Packages
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@otocolobus-com"

      - run: |
          npm version patch --no-git-tag-version
          npm install --prefer-offline --no-audit --progress=false --ignore-scripts

      - run: |
          git config --local user.name "GitHub Actions"
          git add package.json package-lock.json
          git commit -m "Release new version $(node -p "require('./package.json').version") [skip ci]" || echo "No changes to commit"

      - run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git tag v$(node -p "require('./package.json').version")
          git push
          git push --tags

  publish_npm:
    name: Publish package to npm
    runs-on: ubuntu-24.04
    needs: publish_github_packages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"
          scope: "@otocolobus"

      - run: |
          npm pkg set name="$(node -p "require('./package.json').name.replace('@otocolobus-com/', '@otocolobus/')")"
          npm install --prefer-offline --no-audit --progress=false --ignore-scripts

      - run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_REGISTRY_TOKEN }}
